//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonSunMoonRNGTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonSunMoonRNGTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Everstone
        ///Destiny Knot
        ///Power Weight
        ///Power Bracer
        ///Power Belt
        ///Power Lens
        ///Power Band
        ///Power Anklet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_items_en {
            get {
                return ResourceManager.GetString("text_items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変わらず
        ///赤い糸
        ///パワーウエイト
        ///パワーリスト
        ///パワーベルト
        ///パワーレンズ
        ///パワーバンド
        ///パワーアンクル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_items_ja {
            get {
                return ResourceManager.GetString("text_items_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不变之石
        ///红线
        ///力量负重
        ///力量护腕
        ///力量腰带
        ///力量镜
        ///力量束带
        ///力量护踝 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_items_zh {
            get {
                return ResourceManager.GetString("text_items_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame: lower limit &gt; upper limit.
        ///HP: lower limit &gt; upper limit.
        ///Atk: lower limit &gt; upper limit.
        ///Def: lower limit &gt; upper limit.
        ///SpA: lower limit &gt; upper limit.
        ///SpD: lower limit &gt; upper limit.
        ///Spe: lower limit &gt; upper limit.
        ///is out of range.
        ///Genderless Pokémon can only breed with Ditto.
        ///Genderless Pokémon must be entered as ♂ parent when breeding with Ditto.
        ///Accept
        ///eggs and then reject
        ///eggs.
        ///Target frame exceeds the range of list.
        ///is invalid.
        ///doesn&apos;t exist.
        ///Loading default Config.
        ///rows TSV: [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_msgstr_en {
            get {
                return ResourceManager.GetString("text_msgstr_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費数が 下限 ＞上限 になっています。
        ///Hの個体値が 下限 ＞上限 になっています。
        ///Aの個体値が 下限 ＞上限 になっています。
        ///Bの個体値が 下限 ＞上限 になっています。
        ///Cの個体値が 下限 ＞上限 になっています。
        ///Dの個体値が 下限 ＞上限 になっています。
        ///Sの個体値が 下限 ＞上限 になっています。
        ///の上限下限が閾値を超えています。
        ///無性別ポケモンに対し、メタモンが選択されていません。
        ///無性別ポケモンに対し、メタモンは♀親になります。
        ///消費：
        ///回受け取り
        ///回拒否する
        ///目標消費を小さく設定して下さい。
        ///に不正な値が含まれています。
        ///が存在しません。
        ///デフォルトの設定を読み込みます。
        ///番目のTSV：
        ///選択されていません
        ///検索結果からseedを選択して下さい
        ///に保存出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_msgstr_ja {
            get {
                return ResourceManager.GetString("text_msgstr_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帧数下限大于上限。
        ///HP个体值下限大于上限。
        ///攻击个体值下限大于上限。
        ///防御个体值下限大于上限。
        ///特攻个体值下限大于上限。
        ///特防个体值下限大于上限。
        ///速度个体值下限大于上限。
        ///超过范围。
        ///无性别宝可梦 父母一方必须为百变怪。
        ///无性别宝可梦在与百变怪生蛋时应被视作父方。
        ///接受
        ///个蛋后拒绝
        ///次
        ///目标帧数超出列表范围。
        ///不正确。
        ///不存在，
        ///使用默认设置。
        ///行的TSV:
        ///没有选择
        ///请在检索结果中选择Seed。
        ///保存失败。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_msgstr_zh {
            get {
                return ResourceManager.GetString("text_msgstr_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_natures_en {
            get {
                return ResourceManager.GetString("text_natures_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   がんばりや
        ///さみしがり
        ///ゆうかん
        ///いじっぱり
        ///やんちゃ
        ///ずぶとい
        ///すなお
        ///のんき
        ///わんぱく
        ///のうてんき
        ///おくびょう
        ///せっかち
        ///まじめ
        ///ようき
        ///むじゃき
        ///ひかえめ
        ///おっとり
        ///れいせい
        ///てれや
        ///うっかりや
        ///おだやか
        ///おとなしい
        ///なまいき
        ///しんちょう
        ///きまぐれ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_natures_ja {
            get {
                return ResourceManager.GetString("text_natures_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   勤奋
        ///怕寂寞
        ///勇敢
        ///固执
        ///顽皮
        ///大胆
        ///坦率
        ///悠闲
        ///淘气
        ///乐天
        ///胆小
        ///急躁
        ///认真
        ///爽朗
        ///天真
        ///内敛
        ///慢吞吞
        ///冷静
        ///害羞
        ///马虎
        ///温和
        ///温顺
        ///自大
        ///慎重
        ///浮躁 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_natures_zh {
            get {
                return ResourceManager.GetString("text_natures_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_species_en {
            get {
                return ResourceManager.GetString("text_species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タマゴ
        ///フシギダネ
        ///フシギソウ
        ///フシギバナ
        ///ヒトカゲ
        ///リザード
        ///リザードン
        ///ゼニガメ
        ///カメール
        ///カメックス
        ///キャタピー
        ///トランセル
        ///バタフリー
        ///ビードル
        ///コクーン
        ///スピアー
        ///ポッポ
        ///ピジョン
        ///ピジョット
        ///コラッタ
        ///ラッタ
        ///オニスズメ
        ///オニドリル
        ///アーボ
        ///アーボック
        ///ピカチュウ
        ///ライチュウ
        ///サンド
        ///サンドパン
        ///ニドラン♀
        ///ニドリーナ
        ///ニドクイン
        ///ニドラン♂
        ///ニドリーノ
        ///ニドキング
        ///ピッピ
        ///ピクシー
        ///ロコン
        ///キュウコン
        ///プリン
        ///プクリン
        ///ズバット
        ///ゴルバット
        ///ナゾノクサ
        ///クサイハナ
        ///ラフレシア
        ///パラス
        ///パラセクト
        ///コンパン
        ///モルフォン
        ///ディグダ
        ///ダグトリオ
        ///ニャース
        ///ペルシアン
        ///コダック
        ///ゴルダック
        ///マンキー
        ///オコリザル
        ///ガーディ
        ///ウインディ
        ///ニョロモ
        ///ニョロゾ
        ///ニョロボン
        ///ケーシィ
        ///ユンゲラー
        ///フーディン
        ///ワンリキー
        ///ゴーリキー
        ///カイリキー
        ///マダツボミ
        ///ウツドン
        ///ウツボット
        ///メノクラゲ
        ///ドククラゲ
        ///イシツブテ
        ///ゴローン
        ///ゴローニャ
        ///ポニータ
        ///ギャロップ
        ///ヤ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_species_ja {
            get {
                return ResourceManager.GetString("text_species_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   蛋
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_species_zh {
            get {
                return ResourceManager.GetString("text_species_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal
        ///Fighting
        ///Flying
        ///Poison
        ///Ground
        ///Rock
        ///Bug
        ///Ghost
        ///Steel
        ///Fire
        ///Water
        ///Grass
        ///Electric
        ///Psychic
        ///Ice
        ///Dragon
        ///Dark
        ///Fairy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_types_en {
            get {
                return ResourceManager.GetString("text_types_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノーマル
        ///かくとう
        ///ひこう
        ///どく
        ///じめん
        ///いわ
        ///むし
        ///ゴースト
        ///はがね
        ///ほのお
        ///みず
        ///くさ
        ///でんき
        ///エスパー
        ///こおり
        ///ドラゴン
        ///あく
        ///フェアリー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_types_ja {
            get {
                return ResourceManager.GetString("text_types_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般
        ///格斗
        ///飞行
        ///毒
        ///地面
        ///岩石
        ///虫
        ///幽灵
        ///钢
        ///火
        ///水
        ///草
        ///电
        ///超能力
        ///冰
        ///龙
        ///恶
        ///妖精 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string text_types_zh {
            get {
                return ResourceManager.GetString("text_types_zh", resourceCulture);
            }
        }
    }
}
