//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMHatchingRNGTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMHatchingRNGTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string text_natures_en {
            get {
                return ResourceManager.GetString("text_natures_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to がんばりや
        ///さみしがり
        ///ゆうかん
        ///いじっぱり
        ///やんちゃ
        ///ずぶとい
        ///すなお
        ///のんき
        ///わんぱく
        ///のうてんき
        ///おくびょう
        ///せっかち
        ///まじめ
        ///ようき
        ///むじゃき
        ///ひかえめ
        ///おっとり
        ///れいせい
        ///てれや
        ///うっかりや
        ///おだやか
        ///おとなしい
        ///なまいき
        ///しんちょう
        ///きまぐれ.
        /// </summary>
        internal static string text_natures_ja {
            get {
                return ResourceManager.GetString("text_natures_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_species_en {
            get {
                return ResourceManager.GetString("text_species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タマゴ
        ///フシギダネ
        ///フシギソウ
        ///フシギバナ
        ///ヒトカゲ
        ///リザード
        ///リザードン
        ///ゼニガメ
        ///カメール
        ///カメックス
        ///キャタピー
        ///トランセル
        ///バタフリー
        ///ビードル
        ///コクーン
        ///スピアー
        ///ポッポ
        ///ピジョン
        ///ピジョット
        ///コラッタ
        ///ラッタ
        ///オニスズメ
        ///オニドリル
        ///アーボ
        ///アーボック
        ///ピカチュウ
        ///ライチュウ
        ///サンド
        ///サンドパン
        ///ニドラン♀
        ///ニドリーナ
        ///ニドクイン
        ///ニドラン♂
        ///ニドリーノ
        ///ニドキング
        ///ピッピ
        ///ピクシー
        ///ロコン
        ///キュウコン
        ///プリン
        ///プクリン
        ///ズバット
        ///ゴルバット
        ///ナゾノクサ
        ///クサイハナ
        ///ラフレシア
        ///パラス
        ///パラセクト
        ///コンパン
        ///モルフォン
        ///ディグダ
        ///ダグトリオ
        ///ニャース
        ///ペルシアン
        ///コダック
        ///ゴルダック
        ///マンキー
        ///オコリザル
        ///ガーディ
        ///ウインディ
        ///ニョロモ
        ///ニョロゾ
        ///ニョロボン
        ///ケーシィ
        ///ユンゲラー
        ///フーディン
        ///ワンリキー
        ///ゴーリキー
        ///カイリキー
        ///マダツボミ
        ///ウツドン
        ///ウツボット
        ///メノクラゲ
        ///ドククラゲ
        ///イシツブテ
        ///ゴローン
        ///ゴローニャ
        ///ポニータ
        ///ギャロップ
        ///ヤ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_species_ja {
            get {
                return ResourceManager.GetString("text_species_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Fighting
        ///Flying
        ///Poison
        ///Ground
        ///Rock
        ///Bug
        ///Ghost
        ///Steel
        ///Fire
        ///Water
        ///Grass
        ///Electric
        ///Psychic
        ///Ice
        ///Dragon
        ///Dark
        ///Fairy.
        /// </summary>
        internal static string text_types_en {
            get {
                return ResourceManager.GetString("text_types_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノーマル
        ///かくとう
        ///ひこう
        ///どく
        ///じめん
        ///いわ
        ///むし
        ///ゴースト
        ///はがね
        ///ほのお
        ///みず
        ///くさ
        ///でんき
        ///エスパー
        ///こおり
        ///ドラゴン
        ///あく
        ///フェアリー.
        /// </summary>
        internal static string text_types_ja {
            get {
                return ResourceManager.GetString("text_types_ja", resourceCulture);
            }
        }
    }
}
