//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMHatchingRNGTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMHatchingRNGTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! Languages: Save this file accordingly and put it in the same folder as PKHeX&apos;s executable.
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_zh.txt = Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string text_natures_en {
            get {
                return ResourceManager.GetString("text_natures_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to がんばりや
        ///さみしがり
        ///ゆうかん
        ///いじっぱり
        ///やんちゃ
        ///ずぶとい
        ///すなお
        ///のんき
        ///わんぱく
        ///のうてんき
        ///おくびょう
        ///せっかち
        ///まじめ
        ///ようき
        ///むじゃき
        ///ひかえめ
        ///おっとり
        ///れいせい
        ///てれや
        ///うっかりや
        ///おだやか
        ///おとなしい
        ///なまいき
        ///しんちょう
        ///きまぐれ.
        /// </summary>
        internal static string text_natures_ja {
            get {
                return ResourceManager.GetString("text_natures_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勤奋
        ///怕寂寞
        ///勇敢
        ///固执
        ///顽皮
        ///大胆
        ///坦率
        ///悠闲
        ///淘气
        ///乐天
        ///胆小
        ///急躁
        ///认真
        ///爽朗
        ///天真
        ///内敛
        ///慢吞吞
        ///冷静
        ///害羞
        ///马虎
        ///温和
        ///温顺
        ///自大
        ///慎重
        ///浮躁.
        /// </summary>
        internal static string text_natures_zh {
            get {
                return ResourceManager.GetString("text_natures_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_species_en {
            get {
                return ResourceManager.GetString("text_species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タマゴ
        ///フシギダネ
        ///フシギソウ
        ///フシギバナ
        ///ヒトカゲ
        ///リザード
        ///リザードン
        ///ゼニガメ
        ///カメール
        ///カメックス
        ///キャタピー
        ///トランセル
        ///バタフリー
        ///ビードル
        ///コクーン
        ///スピアー
        ///ポッポ
        ///ピジョン
        ///ピジョット
        ///コラッタ
        ///ラッタ
        ///オニスズメ
        ///オニドリル
        ///アーボ
        ///アーボック
        ///ピカチュウ
        ///ライチュウ
        ///サンド
        ///サンドパン
        ///ニドラン♀
        ///ニドリーナ
        ///ニドクイン
        ///ニドラン♂
        ///ニドリーノ
        ///ニドキング
        ///ピッピ
        ///ピクシー
        ///ロコン
        ///キュウコン
        ///プリン
        ///プクリン
        ///ズバット
        ///ゴルバット
        ///ナゾノクサ
        ///クサイハナ
        ///ラフレシア
        ///パラス
        ///パラセクト
        ///コンパン
        ///モルフォン
        ///ディグダ
        ///ダグトリオ
        ///ニャース
        ///ペルシアン
        ///コダック
        ///ゴルダック
        ///マンキー
        ///オコリザル
        ///ガーディ
        ///ウインディ
        ///ニョロモ
        ///ニョロゾ
        ///ニョロボン
        ///ケーシィ
        ///ユンゲラー
        ///フーディン
        ///ワンリキー
        ///ゴーリキー
        ///カイリキー
        ///マダツボミ
        ///ウツドン
        ///ウツボット
        ///メノクラゲ
        ///ドククラゲ
        ///イシツブテ
        ///ゴローン
        ///ゴローニャ
        ///ポニータ
        ///ギャロップ
        ///ヤ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_species_ja {
            get {
                return ResourceManager.GetString("text_species_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蛋
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_species_zh {
            get {
                return ResourceManager.GetString("text_species_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Fighting
        ///Flying
        ///Poison
        ///Ground
        ///Rock
        ///Bug
        ///Ghost
        ///Steel
        ///Fire
        ///Water
        ///Grass
        ///Electric
        ///Psychic
        ///Ice
        ///Dragon
        ///Dark
        ///Fairy.
        /// </summary>
        internal static string text_types_en {
            get {
                return ResourceManager.GetString("text_types_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノーマル
        ///かくとう
        ///ひこう
        ///どく
        ///じめん
        ///いわ
        ///むし
        ///ゴースト
        ///はがね
        ///ほのお
        ///みず
        ///くさ
        ///でんき
        ///エスパー
        ///こおり
        ///ドラゴン
        ///あく
        ///フェアリー.
        /// </summary>
        internal static string text_types_ja {
            get {
                return ResourceManager.GetString("text_types_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///一般
        ///格斗
        ///飞行
        ///毒
        ///地面
        ///岩石
        ///虫
        ///幽灵
        ///钢
        ///火
        ///水
        ///草
        ///电
        ///超能力
        ///冰
        ///龙
        ///恶
        ///妖精.
        /// </summary>
        internal static string text_types_zh {
            get {
                return ResourceManager.GetString("text_types_zh", resourceCulture);
            }
        }
    }
}
